// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0Z8xeqxJbtgVvybRPtm_2YvAkteXrng',
    appId: '1:940336679878:web:8fb18176bd51b05f2fc0c7',
    messagingSenderId: '940336679878',
    projectId: 'lmsiti',
    authDomain: 'lmsiti.firebaseapp.com',
    storageBucket: 'lmsiti.firebasestorage.app',
    measurementId: 'G-XZC81SPGMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOndpT-ncYueOK_Lul6LpzfCXAs8saP04',
    appId: '1:940336679878:android:37e1345ccd8679012fc0c7',
    messagingSenderId: '940336679878',
    projectId: 'lmsiti',
    storageBucket: 'lmsiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncBSXc9svpmj20D6nVYekMkmY_9Le_uA',
    appId: '1:940336679878:ios:a1ff2f9b9842f0f42fc0c7',
    messagingSenderId: '940336679878',
    projectId: 'lmsiti',
    storageBucket: 'lmsiti.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDncBSXc9svpmj20D6nVYekMkmY_9Le_uA',
    appId: '1:940336679878:ios:a1ff2f9b9842f0f42fc0c7',
    messagingSenderId: '940336679878',
    projectId: 'lmsiti',
    storageBucket: 'lmsiti.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs0Z8xeqxJbtgVvybRPtm_2YvAkteXrng',
    appId: '1:940336679878:web:4ff621057731a0582fc0c7',
    messagingSenderId: '940336679878',
    projectId: 'lmsiti',
    authDomain: 'lmsiti.firebaseapp.com',
    storageBucket: 'lmsiti.firebasestorage.app',
    measurementId: 'G-D340F93K53',
  );
}
